module.exports = {
	collectCoverage: true,
	// collectCoverageFrom: ['src/**/*.{ts,tsx}'],
	rootDir: "../",
	collectCoverage: false,
	coverageDirectory: "coverage",
	testEnvironment: "jsdom",
	setupFilesAfterEnv: ["<rootDir>/jest/jest.setup.js"],
	moduleNameMapper: {
		"^@/(.*)$": "<rootDir>/src/$1",
		"^@models/(.*)$": "<rootDir>/src/models/$1",
		"^@hoc/(.*)$": "<rootDir>/src/hoc/$1",
		"^@components/(.*)$": "<rootDir>/src/components/$1",
		"^@assets/(.*)$": "<rootDir>/src/assets/$1",
		"^@interfaces/(.*)$": "<rootDir>/src/interfaces/$1",
		"^@store/(.*)$": "<rootDir>/src/store/$1",
		"^@api/(.*)$": "<rootDir>/src/api/$1",
		"^@core/(.*)$": "<rootDir>/src/core/$1",
		"^@testUtils/(.*)$": "<rootDir>/src/testUtils/$1",
		"\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/jest/mocks/fileMock.js",
		"\\.(css|less)$": "<rootDir>/jest/mocks/fileMock.js",
	},
};